

name: CI/CD with SonarCloud and Deployment

on:
  push:
    branches:
      - main

jobs:
  build-test-sonarcloud:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: |
          cd React_Crudd 
          npm install

      - name: Run SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          organization: hanenbenyounes
          projectKey: SONAR_TOKEN
          token: ${{ secrets.SONAR_TOKEN }}

  deploy:
    needs: build-test-sonarcloud
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/ci-demo-app:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/ci-demo-app:latest

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: <AppServiceName>
          slot-name: production
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: ${{ secrets.DOCKER_USERNAME }}/ci-demo-app:latest
